name: test
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable, beta, nightly ]

    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.rust != 'stable' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: Swatinem/rust-cache@1.3

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-feature-matrix

      - uses: actions-rs/cargo@v1
        with:
          command: feature-matrix
          args: test
